### ISSUE TITLE
7.2.6 compatible?

### ISSUE THREAD

**Issue by bootnumlock** [leen3o/Dialogue#50]
Lee, trying to install this on a 7.2.6 site... pretty naked at this point [was wanting to get the forum in early] the installer just spins. Now, there could be a perms issue? but i did get other packages to install... any thoughts?

**Comment by leen3o** [comment]
Hey bob. I haven't tried it in 7.2.6 to be honest. Does it get through to the 'Almost done' page with a big button? If so, could be a permissions issue with the web.config though, as it makes some changes to it. 

If not, then I'm stumped as it uses package actions to create the tables and then the normal umbraco package installer to create the docTypes etc... 

This is the installer usercontrol that finishes everything off

https://github.com/leen3o/Dialogue/blob/master/Src/Dialogue.Logic/UserControls/DialogueInstaller.ascx.cs

**Comment by bootnumlock** [comment]
think it might be permissions... or something hosed on umbraco setup... trying again... stay tuned

**Comment by bootnumlock** [comment]
yup, it was something with permissions... you can close this issue.
